/**
 * Netlify build — REQUIRED env on Netlify (Site settings → Environment variables):
 *
 *   API_BASE_URL=https://your-api.onrender.com/api   ← recommended (direct calls)
 *     OR
 *   API_PROXY_TARGET=https://your-api.onrender.com   ← same-origin /api proxy
 */
const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '../public');
const isNetlify = Boolean(process.env.NETLIFY || process.env.NETLIFY_DEV);

const apiProxy = process.env.API_PROXY_TARGET?.replace(/\/$/, '');
let apiBaseURL = process.env.API_BASE_URL?.replace(/\/$/, '');

if (apiBaseURL && !apiBaseURL.endsWith('/api')) {
  apiBaseURL = `${apiBaseURL}/api`;
}

const redirects = [];

if (apiProxy) {
  redirects.push(`/api/*  ${apiProxy}/api/:splat  200`);
  if (!apiBaseURL) apiBaseURL = '/api';
  console.log(`✓ API proxy: /api/* → ${apiProxy}/api/*`);
} else if (apiBaseURL) {
  console.log(`✓ Direct API: ${apiBaseURL}`);
} else if (isNetlify) {
  console.error(`
╔══════════════════════════════════════════════════════════════╗
║  NETLIFY BUILD ERROR: API URL not configured                 ║
║                                                              ║
║  Add ONE of these in Netlify → Environment variables:        ║
║    API_BASE_URL = https://YOUR-API.onrender.com/api          ║
║    API_PROXY_TARGET = https://YOUR-API.onrender.com          ║
║                                                              ║
║  Then trigger a new deploy.                                  ║
╚══════════════════════════════════════════════════════════════╝
`);
  process.exit(1);
} else {
  apiBaseURL = '/api';
  console.log('Local build: API → /api (localhost)');
}

redirects.push('/*    /index.html   200');

fs.writeFileSync(
  path.join(publicDir, 'js/config.js'),
  `// Generated by npm run build:netlify — do not edit
window.APP_CONFIG = {
  apiBaseURL: ${JSON.stringify(apiBaseURL)},
};
`
);

fs.writeFileSync(path.join(publicDir, '_redirects'), redirects.join('\n') + '\n');

console.log('Netlify build complete.');
console.log('  config.js apiBaseURL:', apiBaseURL);
console.log('  _redirects:\n', redirects.map((r) => '   ' + r).join('\n'));
