/**
 * Netlify build: inject API URL + optional /api proxy to backend.
 *
 * Netlify env vars:
 *   API_PROXY_TARGET  — e.g. https://your-api.onrender.com (uses same-origin /api)
 *   API_BASE_URL      — e.g. https://your-api.onrender.com/api (direct calls + CORS)
 */
const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '../public');
const apiProxy = process.env.API_PROXY_TARGET?.replace(/\/$/, '');

let apiBaseURL = '/api';
if (apiProxy) {
  apiBaseURL = '/api';
} else if (process.env.API_BASE_URL) {
  apiBaseURL = process.env.API_BASE_URL.replace(/\/$/, '');
  if (!apiBaseURL.endsWith('/api')) apiBaseURL = `${apiBaseURL}/api`;
}

fs.writeFileSync(
  path.join(publicDir, 'js/config.js'),
  `// Generated by npm run build:netlify
window.APP_CONFIG = {
  apiBaseURL: ${JSON.stringify(apiBaseURL)},
};
`
);

let redirects = '/*    /index.html   200\n';
if (apiProxy) {
  redirects = `/api/*  ${apiProxy}/api/:splat  200\n${redirects}`;
  console.log(`Netlify: proxy /api → ${apiProxy}`);
} else {
  console.log(`Netlify: API → ${apiBaseURL}`);
}

fs.writeFileSync(path.join(publicDir, '_redirects'), redirects);
console.log('Netlify build complete.');
