/**
 * Netlify build: writes frontend API config.
 * /api/* is proxied by netlify/functions/api.js using API_PROXY_TARGET (runtime env).
 */
const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '../public');
const apiProxy = process.env.API_PROXY_TARGET?.replace(/\/$/, '');

let apiBaseURL = '/api';

if (!apiProxy && process.env.API_BASE_URL) {
  apiBaseURL = process.env.API_BASE_URL.replace(/\/$/, '');
  if (!apiBaseURL.endsWith('/api')) apiBaseURL = `${apiBaseURL}/api`;
  console.log(`Netlify: direct API → ${apiBaseURL}`);
} else {
  console.log('Netlify: using /api proxy function (set API_PROXY_TARGET in Netlify env)');
}

fs.writeFileSync(
  path.join(publicDir, 'js/config.js'),
  `// Generated by npm run build:netlify
window.APP_CONFIG = {
  apiBaseURL: ${JSON.stringify(apiBaseURL)},
};
`
);

console.log('Netlify build complete.');
